[package]
authors = ["await-ovo <13152410380@163.com>"]
description = "SWC plugin SVGR"
edition = "2021"
license = "MIT"
name = "swc_plugin_svgr"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
regex = "1.8.1"
serde = "1.0"
serde_json = "1.0"
swc_common = { version = "0.31.0", features = ["concurrent"] }
swc_core = { version = "0.75.33", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "ecma_parser",
  "common",
] }
transform_svg_component = { version = "0.1.0", path="../swc-plugin-transform-svg-component/transform"}