[package]
authors = ["await-ovo <13152410380@163.com>"]
description = "SWC plugin for transform DOM elements into react-native-svg components"
edition = "2021"
license = "MIT"
name = "swc_plugin_transform_react_native_svg"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
swc_common = { version = "0.31.0", features = ["concurrent"] }
swc_core = { version = "0.75.33", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }