[package]
description = "AST Transforms for SVGR"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]
license = "MIT"
name = "transform_svg_component"
version = "0.1.0"


[dependencies]
serde = "1.0"
swc_core = { features = [
  "common",
  "ecma_ast",
  "ecma_utils",
  "ecma_visit",
  "ecma_quote",
  "ecma_parser",
  "ecma_transforms",
], version = "0.75.8" }
serde_json = "1"

[dev-dependencies]
swc_core = { features = [
  "testing_transform",
], version = "0.75.8" }