[package]
authors = ["await-ovo <13152410380@163.com>"]
description = "SWC plugin for adding jsx attribute"
edition = "2021"
license = "MIT"
name = "swc_plugin_add_jsx_attribute"
version = "0.12.3"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
swc_common = { version = "0.31.0", features = ["concurrent"] }
swc_core = { version = "0.75.8", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "ecma_parser",
  "common",
] }